### ISSUE TITLE
I am unable to run the jsgrid-webapi project after downloading from github

### ISSUE THREAD

**Issue by Itsathere** [tabalinas/jsgrid-webapi#2]
Can you provide me fresh file link to check each and every functionality of page loading strategy.

**Comment by tabalinas** [comment]
What do you mean by fresh links?
The content of this repo is a working solution.
What kind of issue are you facing with?

**Comment by Itsathere** [comment]
I have downloaded that file but it's not working getting lots of reference error.There is no solution inside the project.that's why i have open it as a website and getting error in global.asax

> Error 1 Could not load type 'JSGridWebAPISample.WebApiApplication'.   C:\Users\ksoft007\Downloads\jsgrid-webapi-master (1)\jsgrid-webapi-master\Global.asax   1

**Comment by tabalinas** [comment]
Why do you call it `file`? Have downloaded entire repo?
Install all required nugets and be sure all refences are available (expand References section in Solution Explorer).

**Comment by Itsathere** [comment]
Yes, I have downloaded but there is no solution inside project.

**Comment by tabalinas** [comment]
It should not matter, just open project file.

**Comment by Itsathere** [comment]
I have open the project file and tried to build the project but getting error in Global.asax.Yes, I have downloaded but there is no solution inside project.What's type of package i need to install from nugets can you give the package list of link where all the required package is there.

**Comment by tabalinas** [comment]
As I mentioned, you need to open Reference section and see missing dependences.

**Comment by Itsathere** [comment]
As i said there is no solution file and also there is no reference section inside project but after right click on project and then clicked on 

> Add>References .

and I have added related references and on button ok click after selecting all references alert message showing 

> The website is already referencing the assembly **Assembly name**
> Do wanna see that project form team viewer or on skype.

**Comment by tabalinas** [comment]
Here are the steps to follow to make it work:
1. Download zip with the repo from github
2. Open `.csproj` file
3. Click `Save All` in VS to save the solution file (save it in the parent directory of the project directory)
4. Click `Build Solution` and VS automatically request all necessary nugets
5. Run the application

**Comment by Itsathere** [comment]
After following your steps still i am facing error and trying to resolve it.
Still package need to install from nuget is

> Install-Package Microsoft.AspNet.Web.Optimization
> 
> Install-Package Microsoft.AspNet.WebApi.Tracing -Version 5.0.0
> 
> Install-Package EntityFramework
> 
> change DB.Entry(client).State = System.Data.Entity.EntityState.Modified;
> to
> DB.Entry(client).State = System.Data.EntityState.Modified;

**Comment by tabalinas** [comment]
Are you sure `packages` directory located not inside project directory but in the upper directory?

**Comment by Itsathere** [comment]
Yes. Btw my requirement is page loading with huge amount of data. If i return 100000 data in one api response then jsgrid will unable to handle it. In the previous issue you told me to about pageLoading: true,`loadData: function(filter) {
                var startIndex = (filter.pageIndex - 1) * filter.pageSize;
                return {
                    data: db.clients.slice(startIndex, startIndex + filter.pageSize),
                    itemsCount: db.clients.length
                };
            }`

tell me how to handle these two parameter inside controller and my problem will resolve.

**Comment by tabalinas** [comment]
Well, the same sequence works for me (I've tested it from scratch). Try to find what you are doing differently.

**Comment by tabalinas** [comment]
Which version of VS do you have? I've tested it with VS 2013. Are ypu sure nugets were fetched?

**Comment by Itsathere** [comment]
VS 2013.Yes.
