### ISSUE TITLE
Uncaught TypeError: Cannot read property 'validate' of undefined

### ISSUE THREAD

**Issue by Itsathere** [tabalinas/jsgrid-webapi#3]
I am trying to validate some fields in jsgrid but after writing code snippet in column like below getting error 
 `fields: [{     name: "ModelNumber", type: "text", width: 120, title: "Model#/Item",
                        validate: function (value, item) {
                            return value.length == 10;
                        }
                    }]`

> Uncaught TypeError: Cannot read property 'validate' of undefined

**Comment by Itsathere** [comment]
Solved it by adding js file 

> jsgrid.validation.js

thanks.

**Comment by tabalinas** [comment]
Glad that you figured it out.

**Comment by Itsathere** [comment]
I am still having problem in page loading with huge data.Can you help me for?

**Comment by tabalinas** [comment]
Do you have an issue regarding this problem?
In any case the best cure for huge data is to avoid loading all the data at once (e.g. using paging).

**Comment by Itsathere** [comment]
Yes. But how to manage data by loading per page. In  [previous problem](https://github.com/tabalinas/jsgrid/issues/300#event-675515471).You have given the link for page loading but I am still not able to understand that issue.Please help me with suitable example or live example.

**Comment by tabalinas** [comment]
Checkout this answer https://github.com/tabalinas/jsgrid/issues/134#issuecomment-154047060. This is what you have to do on the client side. On the server side just request only page of data, e.g. if you are using EF: http://stackoverflow.com/questions/1049825/paging-in-entity-framework
