### ISSUE TITLE
Cannot get the jsgrid-webapi compiled

### ISSUE THREAD

**Issue by patrickwongc8** [tabalinas/jsgrid-webapi#7]
I downloaded the jsgrid-webapi codes, I cannot get it compile. When I resolved the reference, I can see the Grid, but the data is not populated. Please upload the working copy of the web.config. Also upload the changes required to populate the data to the grid. Thank you.

**Comment by tabalinas** [comment]
The uploaded version is a working as-is application. If you didn't change anything, then probably this is a compatibility issue. 
Which version of VS do you use?
Do you run it on development instance of IIS embedded in VS?
For which version of .NET do you compile the app?

**Comment by patrickwongc8** [comment]
I am using VS 2015. I cannot get the clear compile because the unresolved assembly. Please help.

**Comment by tabalinas** [comment]
Which assembly exactly?

**Comment by patrickwongc8** [comment]
Hi Tabalin,
After I got all the reference resolved, it works.
Thanks.
Patrick

**Comment by patrickwongc8** [comment]
Hi Artem,
I have changed the db.js to get the data from the SQL Server. It works. But I cannot get the filter going:
Here is the code:(function () {
        var db = {
            loadData: function (filter) {
                var d = $.Deferred();
                $.ajax({
                    type: "GET",
                    url: 'api/search/GetClientData',
                    data: filter,
                    dataType: "json"
                }).done(function (response) {
                    d.resolve(response);
                    if (filter.Name > "") {
                         response = $.grep(response, function (Client) {
                            return Client.Name == filter.Name;
                               });
                        d.resolve(response);
                    };
                });
                return d.promise();
            }
    }
    window.db = db;
}());
The filter works and returns the correct rows. But it does not refresh the jsGrid.

Do you have any idea what codes that I miss? Thank you.
Patrick

**Comment by patrickwongc8** [comment]
Hi Artem,
I got it working now. It just remove the first 'd.resolve(response);'.
Thanks.
Patrick
